editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: "Zenodo: Publique. Cite. Preserve."
author: "Daniel Vartanian"
keyword: >
  Zenodo. Repositório. Ciência Aberta. Dados Abertos. Reprodutibilidade.
  OpenAIRE. CERN. Sustentarea. USP.
institute: "Universidade de São Paulo"
date: 2026-09-21
date-format: long

website:
  favicon: images/sustentarea-icon.svg
  site-url: https://danielvartan.com/sustentarea-pres-3/
  repo-url: https://github.com/danielvartan/sustentarea-pres-3/
  issue-url: https://github.com/danielvartan/sustentarea-pres-3/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main

format:
  revealjs:
    open-graph: true
    lang: pt-br
    locale: pt
    language: pt-br
    code-link: true
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    preview-links: false
    controls: true
    controls-layout: bottom-right
    slide-number: true
    auto-stretch: true
    fig-align: center
    pdf-max-pages-per-slide: 1
    csl: csl/english-apa-author-date.csl
    theme: [default, brand, scss/styles.scss]
    template-partials:
      - html/title-slide.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false
    include-in-header:
      text: |
        <meta property="og:description" content="">
        <meta property="og:image" content="/sustentarea-pres-3/images/og-image.png">
        <meta property="og:image:height" content="2400">
        <meta property="og:image:width" content="1600">

google-scholar: true
bibliography: references.bib
nocite: "@*"
